namespace Slottet.Shared.DTO;

// Data Transfer Object used to safely transport resident data between the API and the Frontend.
// Contains no business logic or database dependencies.

public class ResidentDto
{
    // The unique identifier for the resident (generated by the database)
    public int Id { get; set; }

    // The initials of the resident
    public string Initial { get; set; } = string.Empty;
}